apiVersion: v1
kind: ServiceAccount
metadata:
  name: connector-sa
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connector-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connector-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: connector-sa
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: connector-role
  apiGroup: rbac.authorization.k8s.io
