apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-agent
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-agent
  template:
    metadata:
      labels:
        app: prefect-agent
    spec:
      serviceAccountName: prefect-agent-sa
      containers:
        - name: prefect-agent
          image: {{ .Values.image.prefectAgent }}
          command: ["prefect", "agent", "kubernetes", "start"]
          env:
            - name: PREFECT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: iit-secrets
                  key: PREFECT_API_KEY
            - name: PREFECT_API_URL
              value: "{{ .Values.prefect.apiUrl }}"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
