apiVersion: v1
kind: Secret
metadata:
  name: iit-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  ALPHAVANTAGE_API_KEY: "{{ .Values.alphavantage.apiKey }}"
  MONGO_INITDB_ROOT_USERNAME: "{{ .Values.mongo.rootUser }}"
  MONGO_INITDB_ROOT_PASSWORD: "{{ .Values.mongo.rootPassword }}"
  PREFECT_API_KEY: "{{ .Values.prefect.apiKey }}"
