apiVersion: apps/v1
kind: Deployment
metadata:
  name: yfinance-service
  namespace: {{ .Values.namespace }}
  labels:
    app: yfinance
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: yfinance
  template:
    metadata:
      labels:
        app: yfinance
    spec:
      serviceAccountName: connector-sa
      containers:
        - name: yfinance
          image: "{{ .Values.image.registry }}/{{ .Values.image.yfinance }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017"
            - name: MONGO_DB
              value: "{{ .Values.namespace }}"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.resources.connectors.requests.cpu }}
              memory: {{ .Values.resources.connectors.requests.memory }}
            limits:
              cpu: {{ .Values.resources.connectors.limits.cpu }}
              memory: {{ .Values.resources.connectors.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: yfinance-service
  namespace: {{ .Values.namespace }}
  labels:
    app: yfinance
spec:
  selector:
    app: yfinance
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
