apiVersion: apps/v1
kind: Deployment
metadata:
  name: alphavantage-service
  namespace: {{ .Values.namespace }}
  labels:
    app: alphavantage
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: alphavantage
  template:
    metadata:
      labels:
        app: alphavantage
    spec:
      serviceAccountName: connector-sa
      containers:
        - name: alphavantage
          image: "{{ .Values.image.registry }}/{{ .Values.image.alphavantage }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8001
          env:
            - name: ALPHAVANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: iit-secrets
                  key: ALPHAVANTAGE_API_KEY
            - name: MONGO_URI
              value: "mongodb://mongo:27017"
            - name: MONGO_DB
              value: "{{ .Values.namespace }}"
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 20
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.resources.connectors.requests.cpu }}
              memory: {{ .Values.resources.connectors.requests.memory }}
            limits:
              cpu: {{ .Values.resources.connectors.limits.cpu }}
              memory: {{ .Values.resources.connectors.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: alphavantage-service
  namespace: {{ .Values.namespace }}
  labels:
    app: alphavantage
spec:
  selector:
    app: alphavantage
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
