name: Release Helm Chart

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4

      - name: Package Helm chart
        run: |
          mkdir -p docs
          helm package iit-helm-chart -d docs

          OWNER=$(echo "${{ github.repository_owner }}")
          REPO=$(echo "${{ github.event.repository.name }}")

          helm repo index docs --url https://${OWNER}.github.io/${REPO}

      - name: Commit and push chart repo updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update Helm chart repo" || echo "No changes to commit"
          git push origin HEAD:main
