name: Release Helm Chart

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # ✅ allow pushing back to repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # ✅ use GitHub token to authenticate

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4

      - name: Package Helm chart
        run: |
          mkdir -p docs
          helm package . -d docs
          helm repo index docs --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

      - name: Commit and push chart repo updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update Helm chart repo" || echo "No changes to commit"
          git push origin HEAD:main
